default: &default
  token:
    secret: secret
    algorithm: HS256
  user_password_encrypt_key: z%C*F-J@NcRfUjXn2r5u8x/A?D(G+KbP 
  vimeo:
    video_post_endpoint: https://api.vimeo.com/me/videos
    authorization_token: 9becc35ba4be2452935d8fbd794e5faa

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
